/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\public\models\GamingRoomBeta.glb --k 
*/

import React from "react";
import { useEffect, useState } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";
// Dynamically import all files matching wallpaper-* in the folder
const importAllWallpapers = () => {
  return [
    "/textures/Wallpaper-1.jpg",
    "/textures/Wallpaper-2.jpg",
    "/textures/Wallpaper-3.jpg",
    "/textures/Wallpaper-4.jpg",
    "/textures/Wallpaper-5.jpg",
  ];
};

export function GamingRoomBeta(props) {
  const textureLoader = new THREE.TextureLoader();
  const { nodes, materials } = useGLTF("models/GamingRoomBeta.glb");

  const texturePaths = importAllWallpapers();

  const textures = texturePaths.map((path) => {
    const texture = textureLoader.load(path, (loadedTexture) => {
      loadedTexture.flipY = false; // Disable flipY for vertical flipping
      loadedTexture.repeat.x = -1; // Flip horizontally
      loadedTexture.offset.x = 1; // Adjust the offset to correct position
    });
    return texture;
  });

  const [currentMaterialIndex, setCurrentMaterialIndex] = useState(0);

  useEffect(() => {
    console.log(texturePaths.length);
    const updateMaterial = () => {
      setCurrentMaterialIndex(
        (prevIndex) => (prevIndex + 1) % texturePaths.length
      );
    };

    const intervalId = setInterval(updateMaterial, 5000);

    return () => clearInterval(intervalId);
  }, []);

  // Create a material based on the current texture
  const dynamicMaterial = new THREE.MeshStandardMaterial({
    map: textures[currentMaterialIndex],
  });

  const texture = useTexture("textures/A.png");
  texture.flipY = false;

  const textureMatrial = new THREE.MeshStandardMaterial({
    map: texture,
  });

  return (
    <group {...props} dispose={null}>
      <group
        name="Sketchfab_model002"
        position={[-0.453, 2.523, -3.1]}
        rotation={[-Math.PI / 2, 0, 0.303]}
        scale={3.22}
      >
        <group
          name="eabfacf2ef9a4a6eb05118f06a45a572fbx"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            name="BOTON_CENTRAL_MAT_Plastic_0"
            geometry={nodes.BOTON_CENTRAL_MAT_Plastic_0.geometry}
            material={materials.MAT_Plastic}
          />
          <mesh
            castShadow
            receiveShadow
            name="polySurface2_MAT_Emission_0"
            geometry={nodes.polySurface2_MAT_Emission_0.geometry}
            material={materials.MAT_Emission}
          />
          <mesh
            castShadow
            receiveShadow
            name="polySurface4_MAT_Details_0"
            geometry={nodes.polySurface4_MAT_Details_0.geometry}
            material={materials.MAT_Details}
          />
          <mesh
            castShadow
            receiveShadow
            name="polySurface5_MAT_Plastic_0"
            geometry={nodes.polySurface5_MAT_Plastic_0.geometry}
            material={materials.MAT_Plastic}
          />
        </group>
      </group>
      <group
        name="Sketchfab_model"
        position={[-1.548, 2.565, -2.538]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.4}
      >
        <group
          name="6f92cb6eda5241e7802090b2a96a129ffbx"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group
            name="Plane007_1"
            position={[52.674, 0, -128.047]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              name="Plane_Material001_0"
              geometry={nodes.Plane_Material001_0.geometry}
              material={materials["Material.009"]}
              position={[-0.877, 0, 0]}
            />
          </group>
        </group>
      </group>
      <group
        name="Sketchfab_model001"
        position={[-1.548, 2.469, -4.016]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.242}
      >
        <group name="led_tvfbx" rotation={[Math.PI / 2, 0, 0]}>
          <group name="led_tv" position={[0.57, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              name="led_tv_phong1_0"
              geometry={nodes.led_tv_phong1_0.geometry}
              material={materials.phong1}
            />
            <mesh
              castShadow
              receiveShadow
              name="led_tv_phong1_0001"
              geometry={nodes.led_tv_phong1_0001.geometry}
              material={dynamicMaterial}
            />
          </group>
        </group>
      </group>
      <group
        name="Sketchfab_model007"
        position={[1.023, 5.923, -3.997]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.266}
      >
        <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
          <group
            name="defaultMaterial255"
            position={[-4.388, 0.127, 0]}
            scale={1.281}
          >
            <mesh
              castShadow
              receiveShadow
              name="defaultMaterial255_1"
              geometry={nodes.defaultMaterial255_1.geometry}
              material={materials.aiStandardSurface3SG}
            />
            <mesh
              castShadow
              receiveShadow
              name="defaultMaterial255_2"
              geometry={nodes.defaultMaterial255_2.geometry}
              material={materials.aiStandardSurface2SG}
            />
            <mesh
              castShadow
              receiveShadow
              name="defaultMaterial255_3"
              geometry={nodes.defaultMaterial255_3.geometry}
              material={materials.aiStandardSurface1SG}
            />
          </group>
        </group>
      </group>
      <group
        name="Sketchfab_model004"
        position={[-1.777, 5.637, -4.15]}
        rotation={[-Math.PI / 2, 0, -0.567]}
        scale={0.015}
      >
        <group
          name="25ca4236319948cba6013ac43008d73bfbx"
          rotation={[Math.PI / 2, 0, 0]}
        >
          <group
            name="Circle000"
            position={[-1.332, 0, -11.309]}
            rotation={[-Math.PI / 2, 0, -0.869]}
            scale={10.02}
          >
            <group
              name="Circle001"
              position={[0, 0, 2.543]}
              rotation={[-0.337, -0.14, 0.38]}
            >
              <group name="Circle005" position={[0, -0.705, -0.882]}>
                <group
                  name="Circle005_Metall_rough_0"
                  position={[9.02, 14.007, -15.504]}
                  rotation={[0.284, -0.355, 1.346]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    name="Circle005_Metall_rough_0_1"
                    geometry={nodes.Circle005_Metall_rough_0_1.geometry}
                    material={materials.Metall_rough}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    name="Circle005_Metall_rough_0_2"
                    geometry={nodes.Circle005_Metall_rough_0_2.geometry}
                    material={materials.Metall}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    name="Circle005_Metall_rough_0_3"
                    geometry={nodes.Circle005_Metall_rough_0_3.geometry}
                    material={materials.Middle}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    name="Circle005_Metall_rough_0_4"
                    geometry={nodes.Circle005_Metall_rough_0_4.geometry}
                    material={materials["material.001"]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <group
        name="Sketchfab_model003"
        position={[-1.51, 5.632, -3.955]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={4.295}
      >
        <group name="Camerafbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            name="DSLR_CameraShape_Dial_2_0_1"
            geometry={nodes.DSLR_CameraShape_Dial_2_0_1.geometry}
            material={materials.Dial_2}
          />
          <mesh
            castShadow
            receiveShadow
            name="DSLR_CameraShape_Dial_2_0_2"
            geometry={nodes.DSLR_CameraShape_Dial_2_0_2.geometry}
            material={materials.Glass}
          />
          <mesh
            castShadow
            receiveShadow
            name="DSLR_CameraShape_Dial_2_0_3"
            geometry={nodes.DSLR_CameraShape_Dial_2_0_3.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            name="DSLR_CameraShape_Dial_2_0_4"
            geometry={nodes.DSLR_CameraShape_Dial_2_0_4.geometry}
            material={materials.Rubber}
          />
          <mesh
            castShadow
            receiveShadow
            name="DSLR_CameraShape_Dial_2_0_5"
            geometry={nodes.DSLR_CameraShape_Dial_2_0_5.geometry}
            material={materials.Screen}
          />
          <mesh
            castShadow
            receiveShadow
            name="DSLR_CameraShape_Dial_2_0_6"
            geometry={nodes.DSLR_CameraShape_Dial_2_0_6.geometry}
            material={materials.Lens}
          />
          <mesh
            castShadow
            receiveShadow
            name="DSLR_CameraShape_Dial_2_0_7"
            geometry={nodes.DSLR_CameraShape_Dial_2_0_7.geometry}
            material={materials.Button}
          />
          <mesh
            castShadow
            receiveShadow
            name="DSLR_CameraShape_Dial_2_0_8"
            geometry={nodes.DSLR_CameraShape_Dial_2_0_8.geometry}
            material={materials.Dial}
          />
          <mesh
            castShadow
            receiveShadow
            name="DSLR_CameraShape_Dial_2_0_9"
            geometry={nodes.DSLR_CameraShape_Dial_2_0_9.geometry}
            material={materials.Lens_Grip}
          />
          <mesh
            castShadow
            receiveShadow
            name="DSLR_CameraShape_Dial_2_0_10"
            geometry={nodes.DSLR_CameraShape_Dial_2_0_10.geometry}
            material={materials.Lens_Outer}
          />
          <mesh
            castShadow
            receiveShadow
            name="DSLR_CameraShape_Dial_2_0_11"
            geometry={nodes.DSLR_CameraShape_Dial_2_0_11.geometry}
            material={materials.Camera_Outer}
          />
          <mesh
            castShadow
            receiveShadow
            name="DSLR_CameraShape_Dial_2_0_12"
            geometry={nodes.DSLR_CameraShape_Dial_2_0_12.geometry}
            material={materials.Back_Outer}
          />
        </group>
      </group>
      <group
        name="Sketchfab_model005"
        rotation={[Math.PI / 2, 0, 0]}
        scale={-0.013}
      >
        <group
          name="Object003_03_-_Default_0"
          position={[-228.616, 249.061, 186.083]}
          rotation={[Math.PI, 0, 0]}
          scale={-1}
        >
          <mesh
            castShadow
            receiveShadow
            name="Object003_03_-_Default_0_1"
            geometry={nodes["Object003_03_-_Default_0_1"].geometry}
            material={materials["03_-_Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            name="Object003_03_-_Default_0_2"
            geometry={nodes["Object003_03_-_Default_0_2"].geometry}
            material={materials["12_-_Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            name="Object003_03_-_Default_0_3"
            geometry={nodes["Object003_03_-_Default_0_3"].geometry}
            material={materials["04_-_Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            name="Object003_03_-_Default_0_4"
            geometry={nodes["Object003_03_-_Default_0_4"].geometry}
            material={materials["07_-_Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            name="Object003_03_-_Default_0_5"
            geometry={nodes["Object003_03_-_Default_0_5"].geometry}
            material={materials.Material_26}
          />
          <mesh
            castShadow
            receiveShadow
            name="Object003_03_-_Default_0_6"
            geometry={nodes["Object003_03_-_Default_0_6"].geometry}
            material={materials["11_-_Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            name="Object003_03_-_Default_0_7"
            geometry={nodes["Object003_03_-_Default_0_7"].geometry}
            material={materials["05_-_Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            name="Object003_03_-_Default_0_8"
            geometry={nodes["Object003_03_-_Default_0_8"].geometry}
            material={materials.Box002__0}
          />
          <mesh
            castShadow
            receiveShadow
            name="Object003_03_-_Default_0_9"
            geometry={nodes["Object003_03_-_Default_0_9"].geometry}
            material={materials["06_-_Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            name="Object003_03_-_Default_0_10"
            geometry={nodes["Object003_03_-_Default_0_10"].geometry}
            material={materials["10_-_Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            name="Object003_03_-_Default_0_11"
            geometry={nodes["Object003_03_-_Default_0_11"].geometry}
            material={materials["08_-_Default"]}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        name="Plane001"
        geometry={nodes.Plane001.geometry}
        material={materials["Material.011"]}
        position={[0, 0.412, 0]}
        scale={4.378}
      />
      <mesh
        castShadow
        receiveShadow
        name="Plane002"
        geometry={nodes.Plane002.geometry}
        material={materials["Material.010"]}
        position={[0, 0.412, 0]}
        scale={4.378}
      />
      <mesh
        castShadow
        receiveShadow
        name="Plane003"
        geometry={nodes.Plane003.geometry}
        material={materials["Material.012"]}
        position={[0, 0.412, 0]}
        scale={4.378}
      />
      <mesh
        castShadow
        receiveShadow
        name="Cube001"
        geometry={nodes.Cube001.geometry}
        material={materials["Material.019"]}
        position={[-4.378, 0.412, -4.378]}
        scale={[0.19, 3.985, 0.19]}
      />
      <mesh
        castShadow
        receiveShadow
        name="Plane006"
        geometry={nodes.Plane006.geometry}
        material={materials["Material.014"]}
        position={[-1.548, 2.506, -3.1]}
        rotation={[0, -1.571, 0]}
        scale={[0.558, 1, 1.703]}
      />
      <mesh
        castShadow
        receiveShadow
        name="Plane005"
        geometry={nodes.Plane005.geometry}
        material={materials["Material.008"]}
        position={[-4.198, 2.456, -2.386]}
        rotation={[0, -1.571, 0]}
        scale={[1, 1, 2.57]}
      />
      <mesh
        castShadow
        receiveShadow
        name="Cube017"
        geometry={nodes.Cube017.geometry}
        material={materials["Material.005"]}
        position={[-4.13, 0.585, -2.938]}
        rotation={[0, -1.571, 0]}
        scale={[0.14, 0.029, 0.015]}
      />
      <group
        name="Cube002"
        position={[1.957, 0.585, -2.938]}
        rotation={[0, -1.571, 0]}
        scale={[0.14, 0.029, 0.116]}
      >
        <mesh
          castShadow
          receiveShadow
          name="Cube002_1"
          geometry={nodes.Cube002_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          name="Cube002_2"
          geometry={nodes.Cube002_2.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          name="Cube002_3"
          geometry={nodes.Cube002_3.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        name="Cube003"
        geometry={nodes.Cube003.geometry}
        material={materials["Material.001"]}
        position={[1.977, 0.585, -2.938]}
        rotation={[0, -1.571, 0]}
        scale={[0.14, 0.029, 0.116]}
      />
      <mesh
        castShadow
        receiveShadow
        name="Cube004"
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[1.977, 0.585, -2.938]}
        rotation={[0, -1.571, 0]}
        scale={[0.14, 0.029, 0.116]}
      />
      <mesh
        castShadow
        receiveShadow
        name="Cube005"
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[1.977, 0.585, -2.938]}
        rotation={[0, -1.571, 0]}
        scale={[0.14, 0.029, 0.116]}
      />
      <mesh
        castShadow
        receiveShadow
        name="Cube006"
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[1.977, 0.585, -2.938]}
        rotation={[0, -1.571, 0]}
        scale={[0.14, 0.029, 0.116]}
      />
      <mesh
        castShadow
        receiveShadow
        name="Cube007"
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[1.977, 0.585, -2.938]}
        rotation={[0, -1.571, 0]}
        scale={[0.14, 0.029, 0.116]}
      />
      <mesh
        castShadow
        receiveShadow
        name="Cube008"
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[1.977, 0.585, -2.938]}
        rotation={[0, -1.571, 0]}
        scale={[0.14, 0.029, 0.116]}
      />
      <mesh
        castShadow
        receiveShadow
        name="Cube009"
        geometry={nodes.Cube009.geometry}
        material={materials["Material.006"]}
        position={[-4.13, 0.585, -2.938]}
        rotation={[0, -1.571, 0]}
        scale={[0.14, 0.029, 0.015]}
      />
      <mesh
        castShadow
        receiveShadow
        name="Plane004"
        geometry={nodes.Plane004.geometry}
        material={textureMatrial}
        position={[-4.198, 2.456, -2.386]}
        rotation={[0, -1.571, 0]}
        scale={[1, 1, 2.57]}
      />
      <mesh
        castShadow
        receiveShadow
        name="Plane008"
        geometry={nodes.Plane008.geometry}
        material={materials["Material.013"]}
        position={[-1.548, 5.635, -4.012]}
        scale={[1.763, 1, 0.388]}
      />
      <group
        name="aButton_aButton1_0"
        position={[0.89, 2.756, -3.524]}
        rotation={[0.551, 0.015, -0.021]}
        scale={[0.027, 0.007, 0.027]}
      >
        <mesh
          castShadow
          receiveShadow
          name="aButton_aButton1_0_1"
          geometry={nodes.aButton_aButton1_0_1.geometry}
          material={materials.aButton1}
        />
        <mesh
          castShadow
          receiveShadow
          name="aButton_aButton1_0_2"
          geometry={nodes.aButton_aButton1_0_2.geometry}
          material={materials.blinn1}
        />
        <mesh
          castShadow
          receiveShadow
          name="aButton_aButton1_0_3"
          geometry={nodes.aButton_aButton1_0_3.geometry}
          material={materials.blinn3}
        />
        <mesh
          castShadow
          receiveShadow
          name="aButton_aButton1_0_4"
          geometry={nodes.aButton_aButton1_0_4.geometry}
          material={materials.blinn2}
        />
        <mesh
          castShadow
          receiveShadow
          name="aButton_aButton1_0_5"
          geometry={nodes.aButton_aButton1_0_5.geometry}
          material={materials.yButton1}
        />
        <mesh
          castShadow
          receiveShadow
          name="aButton_aButton1_0_6"
          geometry={nodes.aButton_aButton1_0_6.geometry}
          material={materials.bButton1}
        />
        <mesh
          castShadow
          receiveShadow
          name="aButton_aButton1_0_7"
          geometry={nodes.aButton_aButton1_0_7.geometry}
          material={materials.xButton1}
        />
      </group>
      <group
        name="Object_34"
        position={[-2.782, 1.608, -2.039]}
        rotation={[-Math.PI, 0.622, -Math.PI]}
        scale={0.032}
      >
        <mesh
          castShadow
          receiveShadow
          name="Object_17"
          geometry={nodes.Object_17.geometry}
          material={materials.Plastic}
        />
        <mesh
          castShadow
          receiveShadow
          name="Object_17_1"
          geometry={nodes.Object_17_1.geometry}
          material={materials.ShinyPlastic}
        />
        <mesh
          castShadow
          receiveShadow
          name="Object_17_2"
          geometry={nodes.Object_17_2.geometry}
          material={materials.LeatherCougar2}
        />
        <mesh
          castShadow
          receiveShadow
          name="Object_17_3"
          geometry={nodes.Object_17_3.geometry}
          material={materials.LeatherCougar}
        />
        <mesh
          castShadow
          receiveShadow
          name="Object_17_4"
          geometry={nodes.Object_17_4.geometry}
          material={materials.Metallic}
        />
        <mesh
          castShadow
          receiveShadow
          name="Object_17_5"
          geometry={nodes.Object_17_5.geometry}
          material={materials.Leather}
        />
        <mesh
          castShadow
          receiveShadow
          name="Object_17_6"
          geometry={nodes.Object_17_6.geometry}
          material={materials.Orange}
        />
        <mesh
          castShadow
          receiveShadow
          name="Object_17_7"
          geometry={nodes.Object_17_7.geometry}
          material={materials["Leather.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          name="Object_17_8"
          geometry={nodes.Object_17_8.geometry}
          material={materials["Leather.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          name="Object_17_9"
          geometry={nodes.Object_17_9.geometry}
          material={materials.Belt}
        />
        <mesh
          castShadow
          receiveShadow
          name="Object_17_10"
          geometry={nodes.Object_17_10.geometry}
          material={materials["Metallic.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        name="Cube010"
        geometry={nodes.Cube010.geometry}
        material={materials["Material.004"]}
        position={[0.882, 0.585, -2.938]}
        rotation={[0, -1.571, 0]}
        scale={[0.14, 0.029, 0.015]}
      />
      <mesh
        castShadow
        receiveShadow
        name="Cube011"
        geometry={nodes.Cube011.geometry}
        material={materials["Material.020"]}
        position={[0.882, 0.585, -2.938]}
        rotation={[0, -1.571, 0]}
        scale={[0.14, 0.029, 0.015]}
      />
    </group>
  );
}

useGLTF.preload("models/GamingRoomBeta.glb");
